@startuml
class Restaurante {
menu: dict
direccion_r: str
pedido (delivery)
descrip_plato (plato)
confirmar (plato, delivery)
agregar (plato, delivery)
}

class Usuario {
correo: str
contraseña: str
nombre: str
direccion_u: str
tipo_pago:str
login (correo,contraseña)

}
class Delivery {
direcciones: lista
hallar_dist (direccion_r,direccion_u)

}

Usuario --* Delivery
Restaurante --* Delivery
Usuario "*"--"1" Restaurante

@enduml