@startuml

Class Restaurante {
menu: dict
direccion_r: str
pedir (delivery)
descrip_plato (plato)
confirmacion (plato, delivery)
agregar (plato, delivery)
}

Class Usuario {
nombre: str
direccion_u: str
login ()
}

Class Delivery {

direccion_u: str
direccion_r: str
hallar_dist (latitud, longitud)

}

Usuario --* Delivery
Restaurante --* Delivery
Usuario "*"--"1" Restaurante

@enduml